---
openapi: 3.0.0
info:
  termsOfService: http://swagger.io/terms/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/vagag/GraphLibraryService/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /computation:
    post:
      summary: Start new graph computation
      operationId: startComputation
      requestBody:
        description: Computation that needs to be performed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Computation'
        required: true
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
components:
  schemas:
    Algorithm:
      type: string
      description: Enumeration of supported algorithms. Should be used everywhere algorithm needs to be specified
      enum:
      - Prim
      - Kruskal
    Graph:
      required:
      - graph
      properties:
        graph:
          type: string
          example: a 1 b 2 c 2
      description: Serilized graph on which the computation should be performed
    Instance:
      type: string
      description: Enumeration of supported instance types. Should be used everywhere instance needs to be specified
      enum:
      - nano
      - micro
      - standard
    Computation:
      required:
      - algorithm
      - graph
      - instance
      - scaling
      type: object
      properties:
        algorithm:
          $ref: '#/components/schemas/Algorithm'
        graph:
          $ref: '#/components/schemas/Graph'
        instance:
          $ref: '#/components/schemas/Instance'
        scaling:
          type: number
          example: 3
      description: Parameters needed to perform an computation
  requestBodies:
    Computation:
      description: Description of the computation that should be performed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Computation'
      required: true
