---
openapi: 3.0.0
info:
  termsOfService: http://swagger.io/terms/
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/vagag/GraphLibraryService/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /algorithm:
    get:
      summary: Return computations that are currently running
      operationId: getAlgorithm
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Algorithm'
  /computation:
    get:
      summary: Return computations that specified by a state
      operationId: getComputations
      parameters:
      - name: state
        in: query
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/State'
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
    post:
      summary: Start new graph computation
      operationId: startComputation
      requestBody:
        description: Computation that needs to be performed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Computation'
        required: true
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
components:
  schemas:
    Algorithm:
      type: string
      description: Enumeration of supported algorithms. Should be used everywhere algorithm needs to be specified
      enum:
      - prim
      - kruskal
    Graph:
      required:
      - data
      properties:
        data:
          type: string
          example: a 1 b 2 c 2
      description: Serilized graph on which the computation should be performed
    State:
      type: string
      description: State of the computation(e.g. Running, Finished)
      enum:
      - ready
      - inProgress
      - finished
    Instance:
      type: string
      description: Enumeration of supported instance types. Should be used everywhere instance needs to be specified
      enum:
      - nano
      - micro
      - standard
    Computation:
      required:
      - algorithm
      - graph
      - instance
      - scaling
      - state
      type: object
      properties:
        algorithm:
          $ref: '#/components/schemas/Algorithm'
        graph:
          $ref: '#/components/schemas/Graph'
        instance:
          $ref: '#/components/schemas/Instance'
        scaling:
          type: number
          example: 3
        state:
          $ref: '#/components/schemas/State'
      description: Parameters needed to perform an computation
  requestBodies:
    Computation:
      description: Description of the computation that should be performed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Computation'
      required: true
